overrides:
- files: "*.ts"
  parser: "@typescript-eslint/parser"
  extends:
  - plugin:@typescript-eslint/recommended
  plugins:
  - "@typescript-eslint"
  env:
    node: true
  rules:
    "@typescript-eslint/explicit-function-return-type": [0]
    "@typescript-eslint/member-delimiter-style":
    - 2
    - multiline:
        delimiter: none
      singleline:
        delimiter: comma