name: CI
on:
  push:
    branches:
    - master
    - release/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: yarn install
    - run: |
        yarn lint
        yarn build
    - run: |
        SET BRANCH=$(git rev-parse --abbrev-ref HEAD)
        yarn upload
